### ISSUE TITLE
Program by měl být v release stavu

### ISSUE THREAD

**Issue by fan1x** [kubic71/Gomoku-multiplayer#1]
- žádný zakomentovaný kód apod... (testovací kód by měl být v GITu)

**Comment by fan1x** [comment]
> Jak to myslíš, testovací kód? Myslíš, že mi tam chybí nějaké unit testy?

To byl jen příklad... Prostě bych chtěl vidět, že ten zdroják bude pěkný jako v release verzi bez nějakých zakomentovaných věcí (důvod pro zakomentované věci jsou většinou, že něco testuješ... Moje poznámka byla vzhledem k tomu, že tohle by v kódu být nemělo - ideálně udělat v GITu testovací branch.

**Comment by kubic71** [comment]
Takže když odstranit zakomentované kusy kódu. Máš ještě nějaké další
připomínky? Je třeba dodělat ještě něco?

**Comment by fan1x** [comment]
> Máš ještě nějaké další připomínky? Je třeba dodělat ještě něco?

Jojo, ještě to procházím... 👍 Napíši Ti sem připomínky a pošlu mail, až to bude všechno
