### ISSUE TITLE
Popsat, jak program zkompilovat na windows

### ISSUE THREAD

**Issue by fan1x** [kubic71/Gomoku-multiplayer#2]
Snažil jsem se to chvíli zprovoznit na Windows, ve VS, pak jsem to vzdat... 👍 Jak to můžu zprovoznit? Popiš to prosím v dokumentaci, jelikož to není úplně trivka... 
Nemusí to nutně být ve VS, jen musím být schopný to relativně zreplikovat, klidně za pomoci VS Code, ...

**Comment by kubic71** [comment]
No právě já jsem taky sám bojoval s tím, jak rozchodit sfml  grafickou
knihovnu, a po chvíli jsem to vzdal a stáhnul jsem si předkofingurovaný
vs-code projekt a postupoval podle návodu zde (
https://github.com/andrew-r-king/sfml-vscode-boilerplate).
