### ISSUE TITLE
Proč nepoužíváš reference?

### ISSUE THREAD

**Issue by fan1x** [kubic71/Gomoku-multiplayer#3]
vector<float> maxn(Board board, char player, char players, int depth, int *move_r, int *move_c);

**Comment by kubic71** [comment]
Objekt Board ve funkci modifikuju, ale nechci, aby byl modifikován výš v
rekurzi.

**Comment by kubic71** [comment]
Teď jsem se nad tím zamyslel, a ve skutečnosti mi to vlastně nevadí, že board bude modifikován.

**Comment by kubic71** [comment]
Ve skutečnosti ani nebude modifikován :)
